### ISSUE TITLE
Failed to install ncurses-devel-6.2.1 dependency

### ISSUE THREAD

**Issue by ghost** [ibhagwan/picom-ibhagwan-template#1]
Hello, thank you for creating this template and for your work  on creating this awesome compton fork! 

Unfortunately I get the following error:

```
=> ERROR: less-551_1: failed to install 'ncurses-devel-6.2_1' dependency! (error 19)
ncurses-libs-6.2_1 in transaction breaks installed pkg `ncurses-6.2_2'
Transaction aborted due to unresolved dependencies.
```
ncurses-devel-6.2.2 is in the repos, but 6.2.1 is needed. I build ncurses-devel-6.2.1 from source and tried to install it:
```
doas xbps-install --repository hostdir/binpkgs ncurses-devel
ncurses-libs-6.2_1 in transaction breaks installed pkg `ncurses-6.2_2'
Transaction aborted due to unresolved dependencies.
```
Removing ncurses 6.2_2 is not a good idea:
```
doas xbps-remove ncurses
ncurses-6.2_2 in transaction breaks installed pkg `base-system-0.113_2'
ncurses-6.2_2 in transaction breaks installed pkg `rxvt-unicode-9.22_12'
Transaction aborted due to unresolved dependencies.
```
I took a look at the template, there are no fixed versions for the dependencies.
Is there something i can do next?

**Comment by ibhagwan** [comment]
You are correct, there are no fixed versions for dependencies in the template.

This was my first interaction with `xbps-src` so the below is more of an “educated guess”: from what you’re describing it seems to me that the package is built inside the void-packages chroot against `ncurses-6.2.1` while your void installation has version `6.2.2` installed.

Instead of replacing your own install ncurses version I would try to install `v6.2.2` inside the void-packages chroot with `xbps-src` and then rebuild the picom template, that way the package will be built against the same ncurses dependency.

Another option would be using a flag with `xbps-install` to install the package only ignoring dependencies, try `—help` and see if such flag exists.

If the above doesn’t work you can simply extract the `picom` binary from your built package and copy it to `/bin` - not an optimal solution but it should work as picom doesn’t need ncurses AFAIK (it’s probably coming from a recursive dependency).


Perhaps it’s also worthwhile asking in the void subreddit as well, I wouldn’t call myself an expert on `xbps-src`.

**Comment by ghost** [comment]
I bumped the version of ncurses up to 6.2.2 in  it's xbps-src template and it just finished compiling. I also had to compile libarchive by using it's template for a successful build process.

Thank you for your hint, it got me on the right track.
